<?php
/**
 * Created by PhpStorm.
 * User: s1hag
 * Date: 8/8/2019
 * Time: 10:46 PM
 */

namespace app\models;


use app\models\rules\EndDateRules;
use Faker\Provider\cs_CZ\DateTime;
use yii\base\Model;

class Activity extends ActivityBase
{

//    public $title;
//    public $description;
//    public $dateStart;
//    public $dateEnd;
//    public $flag;
//    public $isBlocked;
//    public $isRepeatable;

    public const REPEATABLE_TYPE = [
        1 => "Каждый день",
        2 => 'Каждый месяц заданного числа',
        3 => 'Каждую неделю',
        4 => 'Каждый год'
    ];

//    public $repeatableType;
//
//
//    public $isNotifying;
//
//    public $email;


    public function rules()
    {
        return array_merge([
            [['title', 'description'], 'trim'],
            [[
                'title',
                'dateStart',
                'isBlocked',
                'isRepeatable'
            ], 'required'],
            ['dateStart', 'string'],
            ['dateStart', 'date', 'format' => 'php:Y-m-d'],
//            ['dateEnd', EndDateRules::class],
            ['dateEnd', 'endDateValidation'],
            ['description', 'string', 'min' => 5, 'max' => 150],
            ['repeatableType', 'in', 'range' => array_keys(self::REPEATABLE_TYPE)],
            [['isBlocked', 'isRepeatable', 'isNotifying'], 'boolean'],
            ['flag', 'string'],
            ['email', 'email'],
            ['email', 'required', 'when' => function($model){
                return $model->isNotifying?true:false;
            }]
        ], parent::rules());
    }

    public function endDateValidation($attr)
    {
        $this->addError('dateEnd', 'Ваше событие кончается раньше чем началось :(');

        $dateEnd = \DateTime::createFromFormat('d.m.Y H:i', $this->dateEnd);
        $dateStart = \DateTime::createFromFormat('d.m.Y H:i', $this->dateStart);

        if($dateEnd < $dateStart){
            $this->addError('dateEnd', 'Ваше событие кончается раньше чем началось :(');
        }
    }

    public function beforeValidate()
    {

        $date = \DateTime::createFromFormat('d.m.Y H:i', $this->dateStart);
        if($date){
            $this->dateStart=$date->format('Y-m-d');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'title'=>'Название события',
            'description'=>'Описание',
            'dateStart'=>'Начало события',
            'dateEnd'=>'Конец события',
            'isBlocked'=>'Единственное событие на эту дату?',
            'isRepeatable'=>'Событие может повторяться?',
            'flag'=>'Важность события'
        ];
    }
}