<?php
/**
 * Created by PhpStorm.
 * User: s1hag
 * Date: 8/8/2019
 * Time: 10:46 PM
 */

namespace app\models;


use Faker\Provider\cs_CZ\DateTime;
use yii\base\Model;

class Activity extends Model
{
    /**
     * @var string
     * Название события
     */
    public $title;

    /**
     * @var string
     * Описание события
     */
    public $description;

    /**
     * @var int
     * Дата начала события. В Unix timestamp
     */
    public $dateStart;

    /**
     * @var int
     * Дата конца события. В Unix timestamp
     */
    public $dateEnd;

    /**
     * @var string
     * Важность события
     */
    public $flag;

    /**
     * @var boolean
     * Определеяет могут ли быть другие события на эту же дату.
     * true = не могут
     * false = могут
     */
    public $isBlocked;


    /**
     * @var boolean
     * Определеяет может ли событие повторяться
     */
    public $isRepeatable;


    public const REPEATABLE_TYPE = [
        1 => "Каждый день",
        2 => 'Каждый месяц заданного числа',
        3 => 'Каждую неделю',
        4 => 'Каждый год'
    ];

    public $repeatableType;


    public $isNotifying;

    public $email;


    public function rules()
    {
        return [
            [['title', 'description'], 'trim'],
            [[
                'title',
                'dateStart',
                'dateEnd',
                'isBlocked',
                'isRepeatable'
            ], 'required'],
            ['dateStart', 'string'],
            ['dateStart', 'date', 'format' => 'php:Y-m-d'],
            ['dateEnd', 'string'],
            ['description', 'string', 'min' => 5, 'max' => 150],
            ['repeatableType', 'in', 'range' => array_keys(self::REPEATABLE_TYPE)],
            [['isBlocked', 'isRepeatable', 'isNotifying'], 'boolean'],
            ['flag', 'string'],
            ['email', 'email'],
            ['email', 'required', 'when' => function($model){
                return $model->isNotifying?true:false;
            }]
        ];
    }

    public function beforeValidate()
    {

        $date = \DateTime::createFromFormat('d.m.Y H:i', $this->dateStart);
        if($date){
            $this->dateStart=$date->format('Y-m-d');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'title'=>'Название события',
            'description'=>'Описание',
            'dateStart'=>'Начало события',
            'dateEnd'=>'Конец события',
            'isBlocked'=>'Единственное событие на эту дату?',
            'isRepeatable'=>'Событие может повторяться?',
            'flag'=>'Важность события'
        ];
    }
}